FROM saladtechnologies/openmm:cuda11.8

# Copy the simulation.py file to the container image
COPY simulation.py /workspaces/openmm/simulation.py

# Add the kelpie binary to your container image
ADD https://github.com/SaladTechnologies/kelpie/releases/download/0.4.2/kelpie /kelpie
RUN chmod +x /kelpie

# Use kelpie as the "main" command. Kelpie will then execute simulation.py
# with the custom arguments you submit to Kelpie.
CMD ["/kelpie"]